### ISSUE TITLE
Add configuration option for configuring Network Quality

### ISSUE THREAD

**Issue by halvors** [wolveix/satisfactory-server#113]
Add configuration option for configuring Network Quality.

**Comment by msladek** [comment]
The net bandwith is by default already maximised on the server side. Clients can reduce it by changing their local `ini` files. Is there something else that you need to configure?

You can change any parameter server side by editing the ini files in the container's `/home/steam` directory and restarting it.

**Comment by halvors** [comment]
I was thinking about "FG.NetworkQuality 3" documented here: https://satisfactory.fandom.com/wiki/Dedicated_servers under commands, is that the same thing? I think that regulates what it sends (like how often it syncs etc) and not just raw bandwidth.

**Comment by msladek** [comment]
[This Q&A clip](https://www.youtube.com/watch?v=u3Y3HsXyatM) suggests that it's a more user-friendly command-line option for tweaking the network settings that can be found in the `Engine.ini`, `Game.ini` and `Scalability.ini`. You are right it's not just different bandwith options but also tick rates and timeouts. To me it looks like these have already been maximised by default server side, which probably corresponds to the NetworkQuality option Ultra/3. Thus setting `FG.NetworkQuality 3` probably won't change anything, but correct me if I'm mistaken.

Introducing environment variables for all these settings might be overwhelming. Are there some specific ini-settings you want to configure on the server side as environment variables?

Keep in mind that clients have to adjust these options anyway on their local machines (explained [here](https://satisfactory.fandom.com/wiki/Multiplayer#Engine.ini)), otherwise the Satisfactory defaults are applied for this connection regardless of the server settings.

**Comment by halvors** [comment]
@msladek If you say so, but i am pretty sure i noticed that trains etc were a lot smoother when manually entering this command for changing network quality. So in my opinion it should be an environment variable :-)

**Comment by msladek** [comment]
Is it possible that you also changed your local `Options > Gameplay > Network Quality` in the same go?
If no, could you perhaps restart your world in a new container (without executing the `FG.NetworkQuality` command) and check if things are actually less smooth until you execute `FG.NetworkQuality 3`?

I've just tested the different `FG.NetworkQuality` values to see what ini-settings this command influences. My conclusion is that every changed setting is, compared to the defaults we ship with the image, reduced or sometimes equal in the case of `FG.NetworkQuality 3`.

Here are all the setting differences I could identify:
- [FG.NetworkQuality 0](https://pastebin.com/raw/UHia1Z2P)
- [FG.NetworkQuality 1](https://pastebin.com/raw/heJjxmgk)
- [FG.NetworkQuality 2](https://pastebin.com/raw/EnP9279j)
- [FG.NetworkQuality 3](https://pastebin.com/raw/g39EQZ7R)
- [FG.NetworkQuality wolveix/satisfactory-server](https://pastebin.com/raw/d6HSkW8R)

So I don't think `FG.NetworkQuality 3` by itself can improve lagging given our defaults. Still, having a NETWORKQUALITY environment variable would certainly be beneficial for smaller servers that want to reduce network load.

**Comment by wolveix** [comment]
Thanks for handling this @msladek!

To the best of my knowledge, @msladek is correct. The image ships with a far higher value than the command allows you to specify by default. We _could_ add a variable to directly modify this value, but it's already set to max and I'm not sure why you would want to set it any lower, unless it provides a noticeable benefit. 

If you would be so kind, please do try out what @msladek suggested and see whether you experience a quantifiable difference. It could very well be that having a lower value functions better on lower powered servers.

**Comment by halvors** [comment]
@msladek @wolveix I see, thanks for explaining in detail :-) I think you might be right that this could be due to client also changed this setting, would it be beneficial to manually set the same bandwidth limit on the client as since the image exceeds that of the NetworkQuality 3 setting?

Testing smoothness in world is kindof hard as we have a save with a lot going on and differences in smoothness could also be caused by factories starting up etc i think. I have no problem with smothness no matter the NetworkQuality on a blank save, but again then it is not much stuff going on to sync anyway.

**Comment by wolveix** [comment]
You're welcome! (though the credit is almost solely to @msladek)

The value is set to what it is as it's a well-known method to improve multiplayer performance :) Unless there's evidence that lowering it provides an obvious benefit to someone, I don't see the need to do it.

**Comment by msladek** [comment]
@wolveix yes I agree :)
