### ISSUE TITLE
Automatic update on steam new release

### ISSUE THREAD

**Issue by trodix** [wolveix/satisfactory-server#127]
Hi,

If `SKIPUPDATE` is set to `false`, how I know if there is a new update available on steam, to restart the container to download it? Can this is / be done automatically?

**Comment by wolveix** [comment]
Hey :) 

This is handled externally to the container. If `SKIPUPDATE=true`, the container will never update. If `SKIPUPDATE=false` (the default), it will check fo an update on container start. It is recommended to restart the container daily due to instabilities in CSS's server implementation regardless, and I believe this is the responsibility of the orchestrator and not the container itself.

**Comment by trodix** [comment]
Thank's for this answer, I will setup a cron job 👍
