### ISSUE TITLE
FR: Running as non-root via env variable

### ISSUE THREAD

**Issue by samip5** [wolveix/satisfactory-server#220]
It would be good option to have to allow us to specify an env variable to skip the permission updating that requires root so that the container could be run as non-root instead on eg Kubernetes.

**Comment by wolveix** [comment]
Hey @samip5, I appreciate the suggestion. I hate the way that permissions are currently handled. For context, the current iteration came around due to a very high number of users complaining about perms on non-standard deployments or within restricted environments (e.g. Synology devices). Unfortunately, I don't have a restricted environment that I can openly test permissions changes in, which is why I've been hesitant to make any changes given the large number of people that rely on this repo.

I do like the idea of using an environment variable to toggle this behaviour. I'm currently ill, but I'll think the implementation details over soon

**Comment by samip5** [comment]
> I do like the idea of using an environment variable to toggle this behaviour. I'm currently ill, but I'll think the implementation details over soon

I think some apps have an ENV var called `RUNASUID0` or something like that.

**Comment by 98jan** [comment]
preferable in Kubernetes this should be done with the securityContext, would appreciate it if there could be a way to run this container rootless.

If any help is needed for e.g. testing the container or any other related non root issue, you can ping me, would love to see this feature.

**Comment by wolveix** [comment]
@98jan PRs are always welcome! I've been ill for the better part of the last week, and so I haven't had time to properly delve into this. I think the quick and janky way to handle this would be to add an environment variable called `ROOTLESS` or something like that, which is then checked whenever running superuser commands.

I'd _rather_ resolve the core issue, though again, I do not have the restrictive hardware that others do to test this. This image was originally rootless, but was ultimately changed to its current state due to issue after issue about environments which I couldn't personally test within. Removing the `root` dependency is very easy _from a code perspective_, given that it's just a couple of bash scripts :D

**Comment by 98jan** [comment]
Get well soon.

Thanks for your fast reply.
I will try to work on it and see if I can get it working for both options (rootless and non rootless where needed, there are sometimes needed)

**Comment by 98jan** [comment]
created an PR #222 

Open for any questions or ideas on how to make it better.
Tested the changes with my self-made helm chart for satisfactory: https://github.com/98jan/helm-charts/tree/main/charts/satisfactory

**Comment by wolveix** [comment]
@samip5 thanks to @98jan's hard work, this is now achievable by setting `ROOTLESS=true` :)
