### ISSUE TITLE
Feature Request - full image with all game files (the "container" way)

### ISSUE THREAD

**Issue by SnickCH** [wolveix/satisfactory-server#235]
Thank you very much for providing this well documented image. I wanted to start a dedicated server with it and just saw, that the game files are not included in this image. 

**Feature request:** "container way"
- Provide an image with the full game files (directly usable, no additional download or mounting of the "game files"). This means, that the game is already installed (via steamcmd) at the image creation.

The container way is that everything is in the image to use it directly. Especially no additional downloads of the game file. This would help for many operational things. Like updates: Download the new image in the background, restart the container and everything is up to date (because the new image is used). If you change something (in the container) and it goes wrong, you can just create a new container and you are up and running. And for Host with enough power: Have multiple servers on the same host uses only 1 time the space and only needs to download 1time the files.

I am aware that the image will have some GB in size (frankly: I don't know how many GBs). Of course this means some automation in image creation, if not already done. If you need help, I can provide you all information for a gitlab pipeline with gitlab-runners for automated image creation.

You could do this with a second tag so the existing image is not changed. 
Happy automation :)

**Comment by wolveix** [comment]
Hey!

Appreciate the request, but I'm not going to action this. There's been some discussion around this in the past, and while I appreciate your perspective (and generally do all that I can to comply with "the container way"; it's a core element of my job), it's a little flawed specifically for game servers. Upgrading/downgrading client-side is discouraged and often difficult to do, _which is intentional_. As such, it made sense in the beginning (before CSS offered official dedicated server builds and this image relied on client builds) to instead pull on launch, because users _will_ auto-update by default, and they _will_ encounter version mismatches. Of course, yes, you can lock your local and server version, but the average user won't.

It is very common for containers to pull the latest version of the respective service on startup (see the Plex Docker image for example), though it is also common for images to be statically versioned if the service files are small enough for it to make sense (and it usually does). Including the game files would result in the image ballooning to several GB (as you highlighted), which is a major factor as to why many images do _not_ include static files.
