### ISSUE TITLE
Save file is gone after updating Server

### ISSUE THREAD

**Issue by Navok85** [wolveix/satisfactory-server#299]
Please help !!!

It seems that updating the Container will delete your game file.

What I've done

docker compose down
docker compose pull
docker compose up -d

After the Server started , the server is unclaimed. Game is lost

Backups folder is empty, saved folder has a "serverSettings.7777.sav" which seems to be new?

### My Compose file

services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - '/storage/satisfactory:/config'
    environment:
      MAXPLAYERS: 6
      PGID: 1000
      PUID: 1000
    restart: unless-stopped
    healthcheck:
      test: bash /healthcheck.sh
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 14G
        reservations:
          memory: 4G

### Logs

See attached file

[logs.txt](https://github.com/user-attachments/files/16982224/logs.txt)

**Comment by wolveix** [comment]
Hello, unfortunately you ran a version just as 1.0 released which had the bug reported in #266. The bug has been fixed since then, it only affected people who pulled the image within the first few hours of release.

Unfortunately, there's no way to get that data back. Make sure you're fully updated to the latest container image (it should show the version at the top of the logs if so).
