### ISSUE TITLE
Contrainer restarts when the game autosaves

### ISSUE THREAD

**Issue by rooleyzee123** [wolveix/satisfactory-server#302]
### Describe the Bug

When the game Autosaves the container restarts

### Your Runtime Command or Docker Compose File

```shell
services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - './satisfactory-server:/config'
    environment:
      - MAXPLAYERS=8
      - PGID=1000
      - PUID=1000
      - ROOTLESS=false
      - STEAMBETA=false
      - AUTOSAVENUM= 10
    restart: unless-stopped
    healthcheck:
      test: bash /healthcheck.sh
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G

```

### System Specs (please complete the following information):

If you're on Linux, just paste the following block as a single command, and paste the output here.

```shell
===== START ISSUE REPORT =====
OS:  Linux hoth 5.15.0-119-generic #129-Ubuntu SMP Fri Aug 2 19:25:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
CPU: Intel(R) Core(TM) i3-N305
RAM: 19GB/25GB
HDD: 279GB/300GB (98% used)
===== END ISSUE REPORT =====
```

### Logs

Please provide your **full** container logs. Do not link to an external site for them, just upload them as an attachment
to your reply.
[_satisfactory-server_logs export.txt](https://github.com/user-attachments/files/16984434/_satisfactory-server_logs.export.txt)
[_satisfactory-server_logs export 2.txt](https://github.com/user-attachments/files/16984448/_satisfactory-server_logs.export.2.txt)

**Comment by wolveix** [comment]
Hey, that sounds strange! It's almost definitely a game bug, as others are running the server without issues :) 

Could you provide the **full** container log, please? You've provided two partial pieces that don't give a clear picture of what is happening.

**Comment by wickerman123** [comment]
Yup, there's some crash happening on autosave due to a floating point error.

`Generating report for minidump

Application version 5.3.2.0
 ... built from changelist 366202

OS version Linux 4.4.302+ (network name: wolveix-satisfactory-server-1)
Running 4 x86_64 processors (4 logical cores)
Exception was "SIGFPE: floating-point exception"

<SOURCE START>
<SOURCE END>

<CALLSTACK START>
libFactoryServer-FactoryGame-Linux-Shipping.so!AFGGameMode::GenerateNextAutoSaveId() [C:/BuildAgent/work/b731a33f2a691e17/UE4/Engine/Source/./../../FactoryGame/Source/FactoryGame/Private/FGGameMode.cpp:930]
libFactoryServer-FactoryGame-Linux-Shipping.so!UFGSaveSession::Autosave() [C:/BuildAgent/work/b731a33f2a691e17/UE4/Engine/Source/./../../FactoryGame/Source/FactoryGame/Private/FGSaveSession.cpp:1409]
libFactoryServer-Engine-Linux-Shipping.so!FTimerManager::Tick(float) [C:/BuildAgent/work/b731a33f2a691e17/UE4/Engine/Source/./Runtime/Engine/Private/TimerManager.cpp:930]
libFactoryServer-Engine-Linux-Shipping.so!UWorld::Tick(ELevelTick, float) [C:/BuildAgent/work/b731a33f2a691e17/UE4/Engine/Source/./Runtime/Engine/Private/LevelTick.cpp:1585]
libFactoryServer-Engine-Linux-Shipping.so!UGameEngine::Tick(float, bool) [C:/BuildAgent/work/b731a33f2a691e17/UE4/Engine/Source/./Runtime/Engine/Private/GameEngine.cpp:1793]
libFactoryServer-FactoryGame-Linux-Shipping.so!UFGGameEngine::Tick(float, bool) [C:/BuildAgent/work/b731a33f2a691e17/UE4/Engine/Source/./../../FactoryGame/Source/FactoryGame/Private/FGGameEngine.cpp:13]
FactoryServer-Linux-Shipping!FEngineLoop::Tick() [C:/BuildAgent/work/b731a33f2a691e17/UE4/Engine/Source/./Runtime/Launch/Private/LaunchEngineLoop.cpp:5858]
FactoryServer-Linux-Shipping!GuardedMain(char16_t const*) [C:/BuildAgent/work/b731a33f2a691e17/UE4/Engine/Source/./Runtime/Launch/Private/Launch.cpp:190]
libFactoryServer-UnixCommonStartup-Linux-Shipping.so!CommonUnixMain(int, char**, int (*)(char16_t const*), void (*)()) [C:/BuildAgent/work/b731a33f2a691e17/UE4/Engine/Source/./Runtime/Unix/UnixCommonStartup/Private/UnixCommonStartup.cpp:269]
libc.so.6!UnknownFunction(0x29d8f)
libc.so.6!__libc_start_main(+0x7f)
FactoryServer-Linux-Shipping!_start()

<CALLSTACK END>

0 loaded modules

Report end!
`

**Comment by wolveix** [comment]
In which case, please report this to Coffee Stain :) Though this doesn't affect everyone, interestingly.

Feel free to re-open with a **full** container log otherwise!

**Comment by rooleyzee123** [comment]
@wolveix apologies on logs attached is a full log from fresh container to crash
[_satisfactory-server_logs (3).txt](https://github.com/user-attachments/files/16985163/_satisfactory-server_logs.3.txt)

**Comment by wolveix** [comment]
@rooleyzee123 does it still happen with a fresh save?

**Comment by rooleyzee123** [comment]
Submitted to coffee stain

https://questions.satisfactorygame.com/post/66e35154772a987f4a8ae2bf

**Comment by rooleyzee123** [comment]
> @rooleyzee123 does it still happen with a fresh save?

Yeah this happens on both loading a manual save and brand new game

**Comment by wolveix** [comment]
Damn, sorry to hear it :/

**Comment by rooleyzee123** [comment]
No problem, going to attempt to load my friend's save to see if there's some workaround by using a save outside of this to start it

**Comment by rooleyzee123** [comment]
No luck from loading save outside of server saves

also just incase reset max players back to 4 with no luck

**Comment by wickerman123** [comment]
The only fix I have at the moment is to disable auto-saving as manual saving still works. The call stack in the crash long says the last function called was a "GenerateAutoSaveID" function so it seems it's just generating an erroneous value and that's why it's crashing.

**Comment by wolveix** [comment]
I'm curious why it's only affecting certain people. Thanks for the workaround for those affected, @wickerman123!
