### ISSUE TITLE
What to do with a companion management container/script for monitoring and automatic updates

### ISSUE THREAD

**Issue by dfcowell** [wolveix/satisfactory-server#383]
Hi, I was having frustrations with keeping up with game version updates and server maintenance, so I created a companion container for this image to run more sophisticated health checks, version checks and to automatically update the server when updates become available, or restart it when things get slow.

The companion container and script is here: https://github.com/dfcowell/satisfactory-monitor

I'm not really sure what to do about it, since it doesn't neatly fit into what this project is trying to be. It's highly configurable, with lots of escape hatches, and although the defaults match this container image's structure, it could be used for any Satisfactory container image.

The code is MIT licensed, so please feel free to incorporate it into this project if you'd like (or I can open a PR if you're cool with that direction,) or I'm also happy to continue maintaining it in parallel and set up a proper CI/CD pipeline. Looking forward to any feedback.

**Comment by wolveix** [comment]
Hey @dfcowell, really cool project! I'm intrigued as to why you chose JS over something like Go for this, though I imagine you're just more familiar with it :)

I'm against merging this for a couple of reasons. The update check and automated restart should be baked directly into this repo given how disruptive the update process currently is. If we're resorting to a secondary container, Watchtower makes more sense despite only handling "dumb" updates/restarts. The other reason is that it'd become a dependency for the project, and something that would require maintenance and concern moving forward.

If I were to build this directly into the repo, it'd be a self-contained Go binary (if it didn't need Docker socket access, I'd opt for a shell script). I haven't had the time to work on this which is why it's not already a feature, but PRs are always welcome :)

Thanks again!

**Comment by dfcowell** [comment]
Yeah, I hacked it together in JS because it's what I'm familiar with and I could get something out in a hurry, but I've been meaning to dig into Go for a while. If I can find the time I'll take a look at porting it!

Thanks for the feedback.
