### ISSUE TITLE
Server Stuck on Tearing Down World on Second Launch

### ISSUE THREAD

**Issue by psycwolf** [wolveix/satisfactory-server#92]
Hi there!

Having some issues getting a server instance successfully running. 

On first run the server gets to:

`[2021.11.26-13.29.26:723][ 0]LogNet: Browse: /Game/FactoryGame/Map/DedicatedserverEntry?name=Host?sessionName=SatisfactoryServer?Visibility=SV_FriendsOnly?loadgame=savefile?listen?bUseIpSockets`

If the container is restarted then it'll progress as far as:

`[2021.11.26-09.44.19:729][ 0]LogWorld: BeginTearingDown for /Temp/Untitled_0`

but no further.

Please find attached the full log from a clean run.
[FullLog-Satisfactory-CleanRun.txt](https://github.com/wolveix/satisfactory-server/files/7609011/FullLog-Satisfactory-CleanRun.txt)

**Comment by wolveix** [comment]
Hey! Could you please provide your full `docker run` command or `docker-compose.yml` file, please?

**Comment by psycwolf** [comment]
Sure thing:

`docker run -d --name=satisfactory-server -h satisfactory-server -e MAXPLAYERS=4 -e PGID=1000 -e PUID=1000 -e STEAMBETA=false -v C:\Satisfactory-Test:/config -p 7777:7777/udp -p 15000:15000/udp -p 15777:15777/udp wolveix/satisfactory-server:latest`

I get the same behaviour using ubuntu 20 as well (obvs different volume mount parameters).

**Comment by mdreier** [comment]
I got the same behavior, but actually the server is up and running at this point. I also though it was stuck because I could not connect. However, my issue was that the game did not correctly resolve the hostname of my server. Using the IP address instead worked (IPv4), and I could create a game.

**Comment by wolveix** [comment]
@mdreier this is what I expected to be the case, but hadn't had the time to look into it yet. Several other issues have been opened with a similar situation, and it always resolved to the server functioning fine and the issue being somewhere else.

@psycwolf how are you trying to connect to the server in-game?

**Comment by JonEllis** [comment]
I am seeing this too - last log entry being `LogWorld: BeginTearingDown for /Temp/Untitled_0`.

I'm happy to test more stuff, or open a separate issue if my case is different - I'm commenting here because this issue matches how my log file ends - so I assume it matches what step it's likely failing on.

I am certain my firewalls are fine - I have confirmed by stopping the Satisfactory container and listening on udp port 15777 on the host with `nc -u -l 0.0.0.0 15777`, then from another machine send it data with `nc -u my-satisfactory-host 15777`. I see the data arrive fine.

However, when I try to connect to the server in-game, it thinks the server is offline. I have tried both IP and hostname of the server (just in case).

The troubleshooting section [on the wiki](https://satisfactory.fandom.com/wiki/Dedicated_servers#Common_errors_or_problems) says that `pgrep -f FactoryServer.sh` should show pids if the server is successfully running. After execing in (and installing `procps` in the docker container, to get pgrep), it exits without finding any processes.

I just just stopped my satisfactory container, deleted all the data that would be mounted into /config and started it again.
It stopped at `LogWorld: BeginTearingDown for /Temp/Untitled_0` again.

**Comment by psycwolf** [comment]
@wolveix and @mdreier Can confirm, despite the logs not progressing, using the ipv4 address I am able to connect to the server. For my purposes I'm pleased with the outcome and consider the issue closed, thanks to you both for your time and input.

I'll leave the issue marked as open for the convenience of yourself (@wolveix) and @JonEllis though please feel free to close the ticket from here on without my input.

**Comment by wolveix** [comment]
Glad to hear it @psycwolf!

@JonEllis I still believe this is a nwtwork issue rather than server issue. Please provide your full run command or Compose file.

> The troubleshooting section on the wiki says that pgrep -f FactoryServer.sh should show pids if the server is successfully running. After execing in (and installing procps in the docker container, to get pgrep), it exits without finding any processes.

This won't work with this repo.

**Comment by JonEllis** [comment]
Thanks @wolveix, you're probably right about it being my issue!
Also, thanks for confirming that the pgrep won't work for this repo.

I'm starting my container through Ansible, but if I run it directly with docker run, it works fine, so it's not this projects issue.
